@startuml
!procedure $i($icon_type)
    !if ($icon_type == "ok")
        <size:20><color:green><&circle-check></color></size>
    !elseif ($icon_type == "nok")
        <size:20><color:crimson><&circle-x></color></size>
    !elseif ($icon_type == "?")
        <size:20><color:darkorange><&question-mark></color></size>
    !elseif ($icon_type == "i")
        <size:20><color:darkblue><&info></color></size>
    !endif
!endprocedure
@enduml