!function $repeat($char, $times)
    !$ret_val = ""
    !$count = 0

    !while $count<$times
        !$ret_val = $ret_val + $char
        !$count = $count + 1
    !endwhile
    !return $ret_val
!endfunction

!function $rpad($text, $len)
    !return $text + $repeat(" ", $len - %strlen($text))
!endfunction

!function $printText($text, $width = "", $state = "")
    !$color = ""
    !$content = $text

    !if ($state == "disabled")
        !$color = "<color:#BBB>"
    !endif

    !if ($width != "")
        !$content = $rpad($text, $width)
    !endif

    !return $color + $content
!endfunction

!$quart = 12
!$half = $quart * 2 + 1
!$full = $half * 2 + 1

!function $qI($text, $state = "")
    !return '"' + $printText($text, $quart, $state) + '"'
!endfunction

!function $hI($text, $state = "")
    !return '"' + $printText($text, $half, $state) + '"'
!endfunction

!function $fI($text, $state = "")
    !return '"' + $printText($text, $full, $state) + '"'
!endfunction

' deprecated
!function $q($text)
    !return $rpad($text, $quart)
!endfunction

' deprecated
!function $h($text)
    !return $rpad($text, $half)
!endfunction

' deprecated
!function $f($text)
    !return $rpad($text, $full)
!endfunction

!$zero_width_blank = "<U+200B>"
!$pipe = "<U+FF5C>"
!$text_area_width = $zero_width_blank + $repeat(" ", 135) + $zero_width_blank