@startuml
'https://plantuml.com/en/gantt-diagram
'!define IncludesUrl https://raw.githubusercontent.com/cherub-i/plantuml-helpers/main
!define IncludesUrl .
!include IncludesUrl/ressources/colors_iteratec.iuml
!include IncludesUrl/ressources/colors_audi.iuml
!include IncludesUrl/ressources/style_base.iuml

skinparam wrapWidth 300
hide empty members
left to right direction
'top to bottom direction

title Class diagram

class TestAinB {
  Xyz : String
  Baubar : Boolean
  BaubarAb : Date
  BaubarBis : Date
}

TestAinB "0..1" --> "1" SpielMechanik
TestAinB "0..1" ---> "1..*" Aufgaben
@enduml