@startuml
'https://plantuml.com/en/gantt-diagram
'!$IncludesUrl = "https://raw.githubusercontent.com/cherub-i/plantuml-helpers/main"
!$IncludesUrl = "."
!include $IncludesUrl/target/include.iuml

skinparam wrapWidth 300
hide empty members
left to right direction
'top to bottom direction

title Class diagram

class TestAinB {
  Xyz : String
  Baubar : Boolean
  BaubarAb : Date
  BaubarBis : Date
}

TestAinB "0..1" --> "1" SpielMechanik
TestAinB "0..1" ---> "1..*" Aufgaben
@enduml