@startuml
'https://plantuml.com/en/component-diagram
'!$IncludesUrl = "https://raw.githubusercontent.com/cherub-i/plantuml-helpers/main"
!$IncludesUrl = "."
!include $IncludesUrl/target/include.iuml
!include $IncludesUrl/ressources/aws.iuml


skinparam wrapWidth 300
skinparam defaultTextAlignment center

'skinparam linetype polyline
'skinparam linetype ortho
'left to right direction
'top to bottom direction

'variables
!$projectName = Kartenmischmaschine
!$colorApplicationBlock = $grey_light
!$colorApplicationSubBlock = $grey
!$colorApplication = $iteragenta_xlight
!$colorFramework = $iteramint_xlight

'contents
title $projectName - Bausteinsicht Ebene 0

Client(users, "Nutzer", " ")
SSLpadlock(idp, "IDP", " ")
rectangle "$projectName Frontend" as app_fe $colorApplicationBlock
rectangle "$projectName Backend" as app_be $colorApplicationBlock
Aurora(db, "AWS Aurora Database", " ")

[Quartett-Server] as qs

[New Relic Service\n(Monitoring & Metrics)] as nr
CloudWatch(aws_cw, "AWS Cloud Watch", " ")
SimpleStorageServiceBucket(aws_s3, "AWS S3", " ")



users -d-> idp : HTTPS
idp -d-> app_fe : HTTPS
app_fe -d-> app_be : HTTPS
app_be .d.> db : uses

app_be -l-> qs : SFTP

app_be .r.> nr : uses
app_be .ri.> aws_cw : uses
app_be .right.> aws_s3 : uses


' personAlias --> desktopAlias
' desktopAlias --> storageAlias

@enduml