@startmindmap
'https://plantuml.com/en/state-diagram
'!define IncludesUrl https://raw.githubusercontent.com/cherub-i/plantuml-helpers/main
!define IncludesUrl .
!include IncludesUrl/ressources/colors_iteratec.iuml
!include IncludesUrl/ressources/colors_audi.iuml
!include IncludesUrl/ressources/icons.iuml
!include IncludesUrl/ressources/style_base.iuml

* Colors

** Green 
**:But if i
want multiline text?;
**_ Rose without borders no color
*** $NOK this is not ok
*** $OK but this is
*** $Info fyi only
*** $Question well, I don't know either
*** $User I wish, someone whould know

left side

** Blue 
***_:Long text
on the left side
without borders;
@endmindmap