@startmindmap
'https://plantuml.com/en/mindmap-diagram
'!define IncludesUrl https://raw.githubusercontent.com/cherub-i/plantuml-helpers/main
!define IncludesUrl .
!include IncludesUrl/target/include.iuml
!include IncludesUrl/ressources/style_base_as_style.iuml

* Colors

**[#Green] Green 
**:But if i
want multiline text?;
**_:Rose without borders no color
* <size:12>some more details</size>
* <size:12>fyi</size>;
*** $IconNOK this is not ok
*** $IconOK but this is
*** $IconInfo fyi only
*** $IconQuestion well, I don't know either
*** $IconUser I wish, someone whould know

left side

** Blue 
***_:Long text
<size:12>on the left side without borders</size>;
@endmindmap