@startuml
' helpful ressources:
' - https://plantuml.com/de/stdlib#a464d2f6236a5c23
' - https://github.com/plantuml/plantuml-stdlib/tree/master/awslib: use the "git search in this repository" to identify icons you are looking for
'
' usage:
' - include the needed elements in your file after this include, e.g.
'   !include <awslib/General/all>
'   !include <awslib/Database/Aurora>
' - use the forms, e.g.:
'   Aurora(db, "AWS Aurora Database", " ")
'   SimpleStorageServiceBucket(aws_s3, "AWS S3", " ")

!include <awslib14/AWSSimplified>

' redefine AWSEntity, so that labels are not in bold and closer to icon
!definelong AWSEntity(e_alias, e_label, e_techn, e_color, e_sprite, e_stereo)
rectangle "<color:e_color><$e_sprite></color>\ne_label" <<e_stereo>> as e_alias
!enddefinelong


' include commonly used AWS icons
!include <awslib14/General/all>

!include <awslib14/Compute/all>
!include <awslib14/Containers/all>
!include <awslib14/Database/all>
!include <awslib14/DeveloperTools/all>
!include <awslib14/ManagementGovernance/all>
!include <awslib14/NetworkingContentDelivery/all>
!include <awslib14/SecurityIdentityCompliance/all>
!include <awslib14/Storage/all>
@enduml
