@startuml
!$green = "#008450"
!$yellow = "#EFB700"
!$red = "#B81D13"
!$white = "#FFF"
!$grey_xlight = "#EEE"
!$grey_light = "#DDD" 
!$grey = "#BBB"
!$grey_dark = "#999"
!$blue_light = "#99F"

' deprecated
!$Green = $green
!$Yellow = $yellow
!$Red = $red
!$White = $white
!$LightGrey = $grey_light 
!$MidGrey = $grey
!$DarkGrey = $grey_dark
!$LightBlue = $blue_light

' help output
!$showHelp = 1
!if ($showHelp == 1)
    skinparam minClassWidth 200
    skinparam nodesep 10
    skinparam ranksep 10

    rectangle "Base Colors" {
        rectangle "Green" $Green
        rectangle "Yellow" $Yellow
        rectangle "Red" $Red
        rectangle "blue_light" $blue_light

        rectangle "Greys" {
            rectangle "White" $White
            rectangle "grey_xlight" $grey_xlight
            rectangle "grey_light" $grey_light
            rectangle "grey" $grey
            rectangle "grey_dark" $grey_dark
        }
    }
!endif
@enduml