@startuml
!$holidays_bavaria = { "days": [ 
    {"date": "2021-10-03", "name": "Tag der Deutschen Einheit"},
    {"date": "2021-11-01", "name": "Allerheiligen"},
    {"date": "2021-11-17", "name": "Buß- und Bettag"},
    {"date": "2021-12-25", "name": "1. Weihnachtstag"},
    {"date": "2021-12-26", "name": "2. Weihnachtstag"},
    {"date": "2022-01-01", "name": "Neujahr"},
    {"date": "2022-01-06", "name": "Heilige Drei Könige"},
    {"date": "2022-04-15", "name": "Karfreitag"},
    {"date": "2022-04-18", "name": "Ostermontag"},
    {"date": "2022-05-01", "name": "Tag der Arbeit"},
    {"date": "2022-05-26", "name": "Christi Himmelfahrt"},
    {"date": "2022-06-06", "name": "Pfingstmontag"},
    {"date": "2022-06-16", "name": "Fronleichnam"},
    {"date": "2022-08-15", "name": "Mariä Himmelfahrt"},
    {"date": "2022-10-03", "name": "Tag der Deutschen Einheit"},
    {"date": "2022-11-01", "name": "Allerheiligen"},
    {"date": "2022-12-25", "name": "1. Weihnachtsfeiertag"},
    {"date": "2022-12-26", "name": "2. Weihnachtsfeiertag"}
]}
@enduml