@startuml
' https://useiconic.com/open
!$OK =       "<size:20><color:green><&circle-check></color></size>"
!$NOK =      "<size:20><color:crimson><&circle-x></color></size>"
!$Question = "<size:20><color:darkorange><&question-mark></color></size>"
!$Info =     "<size:20><color:darkblue><&info></color></size>"
!$User =     "<size:20><&person></size>"
!$List =     "<size:20><&list></size>"
!$Target =     "<size:20><&target></size>"
@enduml