@startuml
'https://plantuml-documentation.readthedocs.io/en/latest/formatting/all-skin-params.html

!$BackgroundColor = $iteragelb_light
!$BackgroundColorDark = $iteragelb
!$BackgroundColorLight = $iteragelb_xlight
!$LineColor = $iteragenta
!$LineColorLight = "#AAA"

skinparam Legend {
    BackgroundColor $grey_xlight
    BorderColor $grey_xlight
    FontSize 11
}

skinparam Activity {
    StartColor $LineColor
    EndColor $LineColor 
    BackgroundColor $BackgroundColor
    BorderColor $LineColor 
}

skinparam Arrow {
    Color $LineColor
}

skinparam Class {
    HeaderBackgroundColor $BackgroundColor
    BackgroundColor $BackgroundColorLight
    BorderColor $LineColor
}

skinparam Component {
    BackgroundColor $grey
    BorderColor $LineColor
}

skinparam Note {
    TextAlignment left
    BackgroundColor $BackgroundColorLight
    BorderColor $LineColorLight
}

skinparam  Partition {
    BorderColor $LineColorLight
}

skinparam Rectangle {
    BackgroundColor $BackgroundColor
    BorderColor $LineColor 
}

skinparam State {
    StartColor $LineColor
    EndColor $LineColor
    BackgroundColor $BackgroundColorLight
    BorderColor $LineColor
}

<style>
    .transparent {
        BackGroundColor transparent
        LineColor transparent
    }

    mindmapDiagram {
        rootNode {
            FontStyle Bold
            FontSize 20
        }
        node {
            BackgroundColor $BackgroundColorLight
            LineColor $LineColor
            MaximumWidth 200
        }
        ' should work, but does not:
        ' boxless {
        '   Margin 20 20 0 0
        ' }
        arrow {
            LineColor $LineColor
        }
    }
</style>

@enduml