@startuml
'https://plantuml-documentation.readthedocs.io/en/latest/formatting/all-skin-params.html

!$BackgroundColor = $iteragelb_light
!$BackgroundColorDark = $iteragelb
!$BackgroundColorLight = $iteragelb_xlight
!$LineColor = $iteragenta
!$LineColorLight = "#AAA"

<style>
mindmapDiagram {
  rootNode {
    FontStyle Bold
    FontSize 20
  }
  node {
    BackgroundColor $BackgroundColorLight
    LineColor $LineColor
    MaximumWidth 300
  }
  ' should work, but does noz:
  ' boxless {
  '   Margin 20 20 0 0
  ' }
  arrow {
      LineColor $LineColor
  }
}
</style>
@enduml